### ISSUE TITLE
parallel execution

### ISSUE THREAD

**Issue by kevgo** [Originate/text-runner#825]
#### why

- faster execution

#### how

- could use https://www.npmjs.com/package/jest-worker for this

#### configuration

example **text-run.yml** that defines parallel execution:

```yml
files: "{*.md,documentation/**/*.md}"
parallel: true
```

This executes every activity separately by default, in random order.
To run activities sequentially: list the activities to run together, in the order you want to run them.
Activities are referenced as: `<filename>: <activity names>`. A `*` as activity name means all activities in that file.

Run all files in the `tutorial` folder sequentially:

```yml
parallel: true
files: "{*.md,tutorial/**/*.md}"
group:
  - tutorial/**/*.md
```

Run all `start-server` and `stop-server` activities as a sequence:

```yml
parallel: true
files: "{*.md,tutorial/**/*.md}"
group:
  - tutorial/**/*.md: /[start|stop]-server/
```

Run first the `setup` folder, then the `tutorial` folder:

```yml
parallel: true
files: "{*.md,tutorial/**/*.md}"
group:
  - setup/*md
  - tutorial/**/*.md
```
